export class Cgrrcrecm04Model {
    constructor(
                public CTACTE: string,
                public NUMCHQ: string,
                public NSEC: string,
                public NUMSUC: string,
                public CAUSA: string,
                public TIPOR: string,
                public MENSA: string,
                public IMPORT: string,
                public FECREC: string,
                public FECREG: string,
                public PLADIF: string,
                public FECPCH: string,
                public FECDBT: string,
                public FECPM: string,
                public IMPMUL: string,
                public FCDEVO: string,
                public DEVMUL: string,
                public NUMREF: string,
                public FECCIE: string,
                public CUITL1: string,
                public CUITL2: string,
                public CUITL3: string,
                public CUITL4: string,
                public CUITL5: string,
                public CUITL6: string,
                public CUITL7: string,
                public CUITL8: string,
                public CUITL9: string,
                public CUITL0: string,
                public FECENV: string,
                public USERI: string,
                public FECULT: string,
                public USERAU: string,
                public FECAUT: string,
    ) { }
}

